### PR TITLE
Add send packet retries

### PR DESCRIPTION
**Pull request by doronruas**
Add options to retry in case that pcap send packet failed.

### CODE REVIEW

**Comment by royhills** [comment]
How does this pcap retry compare with the backoff and retry when no response is received that is controlled with the --backoff and --retry options?

I'm guessing that this retry is for when libpcap knows it can't send the packet for some reason, so is effectively trying to ensure that exactly one packet gets sent - is that about right?

**Comment by doronruas** [comment]
Yes, you right, I added this feature because I had a problem to send a packet over wireless interface which was busy (Errno: EAGAIN / EBUSY), without this code - in case of EAGAIN / EBUSY the scanning is just stopped without trying again because of this code:
`if (nsent < 0)
      err_sys("ERROR: failed to send packet");`

**Comment by royhills** [comment]
That makes sense.  I normally use wired Ethernet, which is probably why I've never seen this problem. I've merged the code in.

**Comment by doronruas** [comment]
Thanks !

**Pull request merged**
