### PR TITLE
Add MAC override file

### PR DESCRIPTION
**Pull request by obradovic**
* Add --overridefile and -d command-line args
* -d is not super-intuitive but possibly the best remaining option?

### CODE REVIEW

**Comment by obradovic** [comment]
This is a small new feature - just provides the ability to override the MAC vendors for known local addresses.
So instead of say "Sonos, Inc" it can appear as say, "Kitchen Sonos" in the output. 
Please let me know if you have any concerns, happy to address.

**Review by arturoiam — APPROVED** [review]

**Comment by arturoiam** [comment]
Thanks!!! 
Awesome!!

**Review by arturoiam — APPROVED** [review]

**Review by arturoiam — APPROVED** [review]

**Comment by royhills** [comment]
Can the functionality provided by this pull request be achieved by editing the existing mac-vendor.txt file?

If so, perhaps it would make sense to explicitly state that local additions can be added to mac-vendor.txt in the manpage, and add a "# put local changes after this line" at the end of mac-vendor.txt. I think that would be a worthwhile change as I can see that it's something people might want to do, and most probably wouldn't know that mac-vendor.txt can be used for that.  That would be a simple documentation and template change.

**Comment by obradovic** [comment]
> Can the functionality provided by this pull request be achieved by editing the existing mac-vendor.txt file?
> 
> If so, perhaps it would make sense to explicitly state that local additions can be added to mac-vendor.txt in the manpage, and add a "# put local changes after this line" at the end of mac-vendor.txt. I think that would be a worthwhile change as I can see that it's something people might want to do, and most probably wouldn't know that mac-vendor.txt can be used for that. That would be a simple documentation and template change.

Agree, only concern would be updates The `mac-vendor.txt` would get overwritten when a user installs a new version, correct?  And that would then overwrite any local edits they've made?

**Comment by royhills** [comment]
arp-scan will look for the mac-vendor.txt file (and the other mac/vendor mapping files) in the current directory first, and then in the system location (normally /usr/share/arp-scan but depends on the autoconf datadir variable). So if you want a copy that won't get overwritten by an update then you could create a mac-vendor.txt file in the directory you run arp-scan from.

If you change the file in the system location then you are at the mercy of whatever installer you're using.  I'd hope that most would provide some way to preserve local changes - at the very least by renaming the locally changed file out of the way so you can rename it back later or merge the changes back if the new upstream version has updates (very unlikely in this example - mac-vendor.txt hasn't been updated in forever).

I think that the main issue is that it's not obvious that the mac-vendor.txt file can be used to add local mappings, and I'll consider making changes to address that as this is a useful feature.

**Comment by royhills** [comment]
The changes in commits 29535e65bc213196ebf3bbdc3a6966451e0c5f0f and b5e3da6fdbbd7f8f483a4cc7bf43fcd79e476c92 allow the use of normal format mac addresses like 00:50:56:c0:00:08 in the mac-vendor.txt file.  The changes apply to any MAC/Vendor mapping file, so will also apply to the mac-override.txt file in this pull request.

I was trying out your use case as I'd not considered it before, but it was so annoying to have to edit the MAC addresses that I changed the code to support regular MAC addresses that can be cut-and-pasted in directly.

**Comment by royhills** [comment]
PR https://github.com/royhills/arp-scan/pull/91 should address your concern:

> only concern would be updates The mac-vendor.txt would get overwritten when a user installs a new version, correct? And that would then overwrite any local edits they've made?

`mac-vendor.txt` will now be installed to `$(sysconfdir)/$(PACKAGE)` instead of `$(pkgdatadir)`. Package managers should then see this as a configuration file so local changes should be preserved across upgrades.

**Comment by royhills** [comment]
Thank you for your pull request. I'm closing this now as I believe the required functionality has been added to the codebase as detailed in the above comments.  Please open an issue if you find any issues. Thanks.

**Pull request closed without merging**
